sudo: required
services: 
  - docker

before_install:
  - docker build -t sjvasconcello/docker-practice-react -f Dockerfile.dev .

script:
  - docker run sjvasconcello/docker-practice-react npm run test -- --coverage
